import Foundation
import Testing
import TDMCore
@testable import TDMLight

/// The rolls the vectors are stated for.
enum TestFilm {
    static let hp5 = FilmStock.stock(id: "hp5")!
    static let ektar = FilmStock.stock(id: "ektar100")!
    static let delta3200 = FilmStock.stock(id: "delta3200")!
    static let provia = FilmStock.stock(id: "provia100f")!

    static func m6(_ roll: LoadedRoll) -> CameraBodyProfile {
        var body = TestGear.m6
        body.iso = .fixed(roll)
        return body
    }
}

/// `docs/EXPOSURE-MODEL.md` §7a–7d, every row generated by
/// `docs/reference/film-vectors.py`.
@Suite("Film and sensor — EXPOSURE-MODEL §7a–7d")
struct FilmSolverTests {
    /// Bright sun, front-lit, sunlit side: the worked example of §4.
    static let brightSun = 15.10
    /// A lit side street after sunset.
    static let dimStreet = 5.0

    func request(
        ev100: Double,
        roll: LoadedRoll,
        floor: TimeInterval
    ) -> ExposureRequest {
        ExposureRequest(
            ev100: ev100,
            body: TestFilm.m6(roll),
            lens: TestGear.summicron35,
            strategy: .zoneFocus,
            handheldFloor: floor
        )
    }

    func settings(_ outcome: ExposureOutcome) -> [(aperture: Double, shutter: Double)] {
        outcome.recommendations.map { ($0.aperture, (1 / $0.shutter).rounded()) }
    }

    // MARK: §7a — the medium sets the tolerance and the aim

    @Test("Latitude and bias come from the medium, never from the call site")
    func mediumTable() {
        #expect(Medium.blackAndWhiteNegative.latitude == Latitude(overStops: 3.0, underStops: 1.0))
        #expect(Medium.colourNegative.latitude == Latitude(overStops: 3.0, underStops: 1.0))
        #expect(Medium.slide.latitude == Latitude(overStops: 0.5, underStops: 1.0))
        #expect(Medium.digital.latitude == Latitude(overStops: 1.0, underStops: 2.0))

        #expect(abs(Medium.blackAndWhiteNegative.biasEV - 0.33) < 0.01)
        #expect(abs(Medium.colourNegative.biasEV - 0.66) < 0.01)
        #expect(abs(Medium.slide.biasEV - (-0.33)) < 0.01)
        #expect(abs(Medium.digital.biasEV - (-0.33)) < 0.01)
    }

    @Test("A candidate 1.1 stops over is a negative on HP5 and a discard on Provia")
    func latitudeIsAsymmetric() {
        #expect(TestFilm.hp5.medium.latitude.accepts(errorStops: -1.1))
        #expect(!TestFilm.provia.medium.latitude.accepts(errorStops: -1.1))
        // Under-exposure is where negative film runs out first, and both media agree.
        #expect(!TestFilm.hp5.medium.latitude.accepts(errorStops: 1.2))
    }

    @Test("The solver aims at EV_scene − bias, so negative film gets more light")
    func biasedAim() {
        let hp5 = request(ev100: Self.brightSun, roll: LoadedRoll(stock: TestFilm.hp5), floor: 1.0 / 125)
        #expect(abs(hp5.targetEV100 - (Self.brightSun - 1.0 / 3)) < 1e-9)

        let ektar = request(ev100: Self.brightSun, roll: LoadedRoll(stock: TestFilm.ektar), floor: 1.0 / 125)
        #expect(abs(ektar.targetEV100 - (Self.brightSun - 2.0 / 3)) < 1e-9)

        // Slide is aimed a third of a stop *under* the meter, and its over side
        // closes up to protect the highlights.
        let provia = request(ev100: Self.brightSun, roll: LoadedRoll(stock: TestFilm.provia), floor: 1.0 / 125)
        #expect(abs(provia.targetEV100 - (Self.brightSun + 1.0 / 3)) < 1e-9)
        #expect(provia.tolerance.overStops == 0.5)
    }

    // MARK: §7b — what a fixed roll admits

    @Test("Bright sun on HP5 400 admits exactly two settings")
    func brightSunOnHP5() throws {
        let outcome = ExposureSolver.resolve(
            request(ev100: Self.brightSun, roll: LoadedRoll(stock: TestFilm.hp5), floor: 1.0 / 125)
        )
        let solution = try #require(outcome.solution)
        #expect(solution.count == 2)

        let found = settings(outcome)
        #expect(found.contains { $0.aperture == 16 && $0.shutter == 500 })
        #expect(found.contains { $0.aperture == 11 && $0.shutter == 1_000 })
    }

    @Test("The same sun on Ektar 100 admits four, f/16 · 1/125 through f/5.6 · 1/1000")
    func brightSunOnEktar() throws {
        let outcome = ExposureSolver.resolve(
            request(ev100: Self.brightSun, roll: LoadedRoll(stock: TestFilm.ektar), floor: 1.0 / 125)
        )
        let solution = try #require(outcome.solution)
        #expect(solution.count == 4)

        let found = settings(outcome)
        for expected in [(16.0, 125.0), (11.0, 250.0), (8.0, 500.0), (5.6, 1_000.0)] {
            #expect(found.contains { $0.aperture == expected.0 && $0.shutter == expected.1 })
        }
    }

    @Test("A dim street on HP5 400 has no answer, and the shortfall is 0.9 stops")
    func dimStreetOnHP5() throws {
        let outcome = ExposureSolver.resolve(
            request(ev100: Self.dimStreet, roll: LoadedRoll(stock: TestFilm.hp5), floor: 1.0 / 35)
        )
        let shortfall = try #require(outcome.shortfall)

        #expect(abs(shortfall.stops - 0.91) <= 0.02)
        #expect(shortfall.sense == .needsMoreLight)
        #expect(shortfall.isSalvageable)
        // The reason is the answer: an empty list would say nothing.
        #expect(outcome.recommendations.isEmpty)
        #expect(shortfall.closest != nil)
    }

    @Test("The first lever is the roll: HP5 pushed two stops to 1600")
    func dimStreetLevers() throws {
        let outcome = ExposureSolver.resolve(
            request(ev100: Self.dimStreet, roll: LoadedRoll(stock: TestFilm.hp5), floor: 1.0 / 35)
        )
        let shortfall = try #require(outcome.shortfall)
        let first = try #require(shortfall.levers.first)

        guard case let .rate(roll, setting) = first else {
            Issue.record("The first lever should be the roll, per §7b")
            return
        }
        #expect(roll.ratedAt == 1_600)
        #expect(abs(roll.pushStops - 2) < 1e-9)
        #expect(roll.cost == "Coarse grain, blocked shadows.")

        // The lever carries the setting the push buys, solved under the same
        // strategy — zone focus prefers the narrower of the two, f/2.8 · 1/60.
        let pushed = try #require(setting)
        #expect(pushed.aperture == 2.8)
        #expect(abs(1 / pushed.shutter - 60) < 0.5)

        // And the second is the floor, which the mockup states as 1/30.
        #expect(shortfall.levers.contains { lever in
            if case let .lowerFloor(shutter, _) = lever { return abs(shutter - 1.0 / 30) < 1e-12 }
            return false
        })
    }

    @Test("HP5 rated at 1600 admits f/2.8 · 1/60 and f/2 · 1/125")
    func dimStreetPushedToSixteenHundred() throws {
        let roll = LoadedRoll(stock: TestFilm.hp5, ratedAt: 1_600)
        let outcome = ExposureSolver.resolve(request(ev100: Self.dimStreet, roll: roll, floor: 1.0 / 35))
        let solution = try #require(outcome.solution)
        #expect(solution.count == 2)

        let found = settings(outcome)
        #expect(found.contains { $0.aperture == 2.8 && $0.shutter == 60 })
        #expect(found.contains { $0.aperture == 2 && $0.shutter == 125 })
        #expect(roll.displayName == "HP5 400 @ 1600 (+2)")
    }

    @Test("Delta 3200 on the same street admits three")
    func dimStreetOnDelta() throws {
        let outcome = ExposureSolver.resolve(
            request(ev100: Self.dimStreet, roll: LoadedRoll(stock: TestFilm.delta3200), floor: 1.0 / 35)
        )
        let solution = try #require(outcome.solution)
        #expect(solution.count == 3)

        let found = settings(outcome)
        #expect(found.contains { $0.aperture == 4 && $0.shutter == 60 })
        #expect(found.contains { $0.aperture == 2.8 && $0.shutter == 125 })
        #expect(found.contains { $0.aperture == 2 && $0.shutter == 250 })
    }

    // MARK: §7d — ISO as the solved variable

    @Test("A dim street at f/2 · 1/125 needs ISO 1562, so the M10 is set to 1600")
    func digitalISOFreezingAWalk() throws {
        let solved = try #require(
            ExposureSolver.solveISO(
                ev100: Self.dimStreet,
                aperture: 2,
                shutter: 1.0 / 125,
                availability: TestGear.m10.iso
            )
        )
        #expect(abs(solved.exact - 1_562) <= 1)
        #expect(solved.iso == 1_600)
        #expect(!solved.exceedsCeiling)
    }

    @Test("The same street at f/2 · 1/60 needs ISO 750, rounded up to 800")
    func digitalISOAtSixty() throws {
        let solved = try #require(
            ExposureSolver.solveISO(
                ev100: Self.dimStreet,
                aperture: 2,
                shutter: 1.0 / 60,
                availability: TestGear.m10.iso
            )
        )
        #expect(abs(solved.exact - 750) <= 1)
        #expect(solved.iso == 800)
    }

    @Test("The rounding is always up: down is under-exposure by habit")
    func digitalISORoundsUp() throws {
        let ladder = ISOAvailability.range(minimum: 100, maximum: 6_400)
        for (shutter, expected) in [(1.0 / 125, 1_600), (1.0 / 60, 800), (1.0 / 250, 3_200)] {
            let solved = try #require(
                ExposureSolver.solveISO(
                    ev100: Self.dimStreet,
                    aperture: 2,
                    shutter: shutter,
                    availability: ladder
                )
            )
            #expect(solved.iso == expected)
            #expect(Double(solved.iso) >= solved.exact)
        }
    }

    @Test("A ceiling is reported as a shortfall rather than exceeded")
    func digitalCeiling() throws {
        let capped = ISOAvailability.range(minimum: 100, maximum: 50_000, ceiling: 800)
        let solved = try #require(
            ExposureSolver.solveISO(
                ev100: Self.dimStreet,
                aperture: 2,
                shutter: 1.0 / 125,
                availability: capped
            )
        )
        #expect(solved.iso == 800)
        #expect(solved.exceedsCeiling)
        #expect(capped.solvableValues == [100, 200, 400, 800])
    }

    @Test("The ceiling, not the sensor, is offered as the lever")
    func raiseTheCeiling() throws {
        var body = TestGear.m10
        body.iso = .range(minimum: 100, maximum: 6_400, ceiling: 100)
        let outcome = ExposureSolver.resolve(
            ExposureRequest(
                ev100: Self.dimStreet,
                body: body,
                lens: TestGear.summicron35,
                strategy: .zoneFocus,
                handheldFloor: 1.0 / 35
            )
        )
        let shortfall = try #require(outcome.shortfall)
        #expect(shortfall.levers.contains { lever in
            if case let .raiseCeiling(iso) = lever { return iso > 100 }
            return false
        })
    }

    // MARK: §7b — the aperture that is off the dial

    @Test("f/2 in bright sun on ISO 400 needs 1/35 120 s — no M has it")
    func wideOpenInBrightSun() throws {
        for body in [TestGear.m6, TestGear.m10] {
            let unreachable = try #require(
                ExposureSolver.unreachableAperture(
                    ev100: Self.brightSun,
                    aperture: 2,
                    iso: 400,
                    body: body
                )
            )
            #expect(abs(1 / unreachable.requiredShutter - 35_120) <= 60)
            #expect(unreachable.neutralDensityStops > 3)
        }
    }

    @Test("Isolating a subject in bright sun says so rather than narrowing the aperture")
    func isolationStatesTheLimit() throws {
        var isolation = request(
            ev100: Self.brightSun,
            roll: LoadedRoll(stock: TestFilm.hp5),
            floor: 1.0 / 125
        )
        isolation.strategy = .subjectIsolation

        let solution = try #require(ExposureSolver.resolve(isolation).solution)
        let wideOpen = try #require(solution.wideOpen)
        #expect(wideOpen.aperture == 2)
        #expect(1 / wideOpen.requiredShutter > 4_000)
        // The settings offered are still real ones — the limit is stated beside
        // them, not instead of them.
        #expect(solution.primary.aperture > 2)
    }
}

/// The words the two modes and the no-solution screen are made of.
@Suite("Phrasing — film and sensor")
struct FilmPhrasingTests {
    @Test("A shortfall reads as a sentence about the roll, not as an empty list")
    func shortfallSentence() throws {
        let request = ExposureRequest(
            ev100: 5.0,
            body: TestFilm.m6(LoadedRoll(stock: TestFilm.hp5)),
            lens: TestGear.summicron35,
            strategy: .zoneFocus,
            handheldFloor: 1.0 / 35
        )
        let shortfall = try #require(ExposureSolver.resolve(request).shortfall)

        #expect(
            ExposurePhrasing.shortfallSentence(shortfall, roll: request.body.loadedRoll)
                == "HP5 400 is 0.9 stops short here."
        )
        #expect(ExposurePhrasing.stops(1.0) == "1 stop")
        #expect(ExposurePhrasing.stops(2.02) == "2 stops")
    }

    @Test("Each lever says what it is and what it costs")
    func leverWords() {
        let push = ExposureLever.rate(roll: LoadedRoll(stock: TestFilm.hp5, ratedAt: 1_600), setting: nil)
        #expect(ExposurePhrasing.leverTitle(push) == "Push the roll to 1600")
        #expect(ExposurePhrasing.leverDetail(push).hasPrefix("+2 stops · coarse grain, blocked shadows"))

        let floor = ExposureLever.lowerFloor(shutter: 1.0 / 30, setting: nil)
        #expect(ExposurePhrasing.leverTitle(floor) == "Drop to 1/30")
        #expect(ExposurePhrasing.leverDetail(floor, floor: 1.0 / 35) == "Below the 1/35 floor · moving subjects will smear")

        #expect(ExposurePhrasing.leverTitle(.raiseCeiling(toISO: 3_200)) == "Raise the ISO ceiling to 3200")
        #expect(ExposurePhrasing.leverTitle(.neutralDensity(stops: 3)) == "Put on a 3-stop ND")
        #expect(ExposurePhrasing.leverTitle(.differentRoll(isoSpeed: 3_200)) == "Load something faster — ISO 3200")
    }

    @Test("Digital phrases the ISO as a change, film as context")
    func isoWords() {
        #expect(ExposurePhrasing.raiseISO(to: 1_600) == "Raise ISO to 1600")
        #expect(
            ExposurePhrasing.loadedRoll(LoadedRoll(stock: TestFilm.hp5, ratedAt: 1_600))
                == "HP5 400 @ 1600 (+2)"
        )
    }
}
